# fly.toml app configuration file generated for ecommerce-node-react-app on 2023-07-07T20:00:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ecommerce-node-react-app"
primary_region = "lhr"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
